# Default values for go-web-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nayanjk/go-web-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "29083458340"
  tag: "29083458340"

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific



# tag: "29083458340"
# So what happens is, every time the CI/CD is run, we'll update the Values.yaml with the latest image that we create during the CI 
# And with the help of ArgoCD the image with the latest tag will be deployed

