apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-web-app
  name: go-web-app
spec:
  ports:
  - port: 80          # Port of the Service
    protocol: TCP
    targetPort: 8080  # Port of the application
  selector:
    app: go-web-app
  type: ClusterIp
  # type: NodePort

